# Generated by Django 6.0.2 on 2026-02-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'دفع إلكتروني'), ('COD', 'دفع عند الاستلام')], default='ONLINE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'انتظار'), ('PAID', 'تم الدفع'), ('SHIPPED', 'شحن'), ('DELIVERED', 'تم')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('description', models.TextField(verbose_name='وصف المنتج')),
                ('image', models.ImageField(upload_to='products/', verbose_name='صورة المنتج')),
                ('stock', models.IntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('price_sar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر بالريال السعودي')),
                ('price_aed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر بالدرهم الإماراتي')),
                ('price_kwd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='السعر بالدينار الكويتي')),
                ('price_bhd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='السعر بالدينار البحريني')),
                ('price_omr', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='السعر بالريال العماني')),
                ('price_qar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر بالريال القطري')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
